/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  DATE_PREFIX_REGEX: () => DATE_PREFIX_REGEX,
  MOOD_LEVELS: () => MOOD_LEVELS,
  computeEntrySpans: () => computeEntrySpans,
  default: () => DaylioGraphPlugin,
  groupByDay: () => groupByDay,
  isMoodLevel: () => isMoodLevel,
  parseCsvLine: () => parseCsvLine,
  parseDaylioCsv: () => parseDaylioCsv,
  scanVaultEvents: () => scanVaultEvents
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/log.ts
var log = (...args) => console.debug("[daylio]", ...args);
var log_default = log;

// src/types.ts
var import_obsidian = require("obsidian");

// src/daylio-face.svg
var daylio_face_default = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">\n  <circle cx="50" cy="50" r="48" fill="#4CAF50"/>\n  <circle cx="30" cy="52" r="7" fill="#1a1a1a"/>\n  <circle cx="70" cy="52" r="7" fill="#1a1a1a"/>\n  <path d="M35 65 Q50 74 65 65" stroke="#1a1a1a" stroke-width="7" fill="none" stroke-linecap="round"/>\n</svg>\n';

// src/types.ts
var DAYLIO_ICON_ID = "daylio-face";
var _a, _b;
var svgInner = (_b = (_a = daylio_face_default.match(/<svg[^>]*>([\s\S]*)<\/svg>/i)) == null ? void 0 : _a[1]) != null ? _b : daylio_face_default;
(0, import_obsidian.addIcon)(DAYLIO_ICON_ID, svgInner);
var MOOD_LEVELS = ["awful", "bad", "meh", "good", "rad"];
var DEFAULT_MOOD_COLORS = {
  rad: "#f78c1e",
  good: "#41a766",
  meh: "#9056a3",
  bad: "#5579a7",
  awful: "#6a777c"
};
var DEFAULT_SETTINGS = {
  csvPath: "",
  moodColors: { ...DEFAULT_MOOD_COLORS },
  barWidth: 8,
  eventScanDir: ""
};
var VIEW_TYPE_DAYLIO = "daylio-mood-graph-view";
function barGapFor(barWidth) {
  return barWidth >= 2 ? 2 : barWidth >= 1 ? 1 : 0;
}
var MOOD_TO_LANE = {
  rad: 0,
  good: 1,
  meh: 2,
  bad: 3,
  awful: 4
};

// src/graph-view.ts
var import_obsidian2 = require("obsidian");

// src/csv-parser.ts
function parseDaylioCsv(raw) {
  var _a2, _b2, _c, _d, _e, _f;
  const lines = raw.split(/\r?\n/).filter((line) => line.trim() !== "");
  log_default("parseDaylioCsv: non-empty lines (including header):", lines.length);
  if (lines.length < 2) {
    log_default("parseDaylioCsv: too few lines, returning empty array");
    return [];
  }
  const entries = [];
  let skippedRows = 0;
  for (let i = 1; i < lines.length; i++) {
    const fields = parseCsvLine((_a2 = lines[i]) != null ? _a2 : "");
    const fullDate = (_b2 = fields[0]) == null ? void 0 : _b2.trim();
    const time = (_d = (_c = fields[3]) == null ? void 0 : _c.trim()) != null ? _d : "";
    const moodRaw = (_f = (_e = fields[4]) == null ? void 0 : _e.trim().toLowerCase()) != null ? _f : "";
    if (!fullDate || !isMoodLevel(moodRaw)) {
      skippedRows++;
      continue;
    }
    entries.push({ date: fullDate, time, mood: moodRaw });
  }
  log_default(
    "parseDaylioCsv: parsed",
    entries.length,
    "entries,",
    skippedRows,
    "data rows skipped (missing date or unrecognised mood)"
  );
  return entries;
}
function parseCsvLine(line) {
  const result = [];
  let current = "";
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const char = line[i];
    if (inQuotes) {
      if (char === '"') {
        if (i + 1 < line.length && line[i + 1] === '"') {
          current += '"';
          i++;
        } else {
          inQuotes = false;
        }
      } else {
        current += char;
      }
    } else {
      if (char === '"') {
        inQuotes = true;
      } else if (char === ",") {
        result.push(current);
        current = "";
      } else {
        current += char;
      }
    }
  }
  result.push(current);
  return result;
}
function isMoodLevel(value) {
  return MOOD_LEVELS.includes(value);
}
function groupByDay(entries) {
  log_default("groupByDay: grouping", entries.length, "entries");
  const map = /* @__PURE__ */ new Map();
  for (const entry of entries) {
    const existing = map.get(entry.date);
    if (existing) {
      existing.push(entry);
    } else {
      map.set(entry.date, [entry]);
    }
  }
  const days = [];
  for (const [date, dayEntries] of map) {
    dayEntries.sort((a, b) => a.time.localeCompare(b.time));
    days.push({ date, entries: dayEntries });
  }
  days.sort((a, b) => a.date.localeCompare(b.date));
  log_default("groupByDay: result is", days.length, "unique days");
  return days;
}

// src/vault-scanner.ts
var DATE_PREFIX_REGEX = /^(\d{4}-\d{2}-\d{2})/;
function scanVaultEvents(app, scanDir) {
  var _a2;
  log_default(
    "scanVaultEvents: scanning",
    scanDir ? `directory "${scanDir}"` : "whole vault"
  );
  const events = [];
  const prefix = scanDir ? scanDir.replace(/\/+$/, "") + "/" : null;
  const files = app.vault.getMarkdownFiles().filter(
    (f) => prefix === null || f.path.startsWith(prefix)
  );
  log_default("scanVaultEvents: examining", files.length, "markdown files");
  for (const file of files) {
    const dateMatch = file.basename.match(DATE_PREFIX_REGEX);
    if (!(dateMatch == null ? void 0 : dateMatch[1])) continue;
    const cache = app.metadataCache.getFileCache(file);
    const eventValue = (_a2 = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a2["daylio_event"];
    const label = typeof eventValue === "string" && eventValue.trim() ? eventValue.trim() : void 0;
    if (label) {
      log_default("scanVaultEvents: labelled entry:", dateMatch[1], "\u2192", label);
    } else {
      log_default("scanVaultEvents: unlabelled entry:", dateMatch[1]);
    }
    events.push({
      date: dateMatch[1],
      label,
      filePath: file.path
    });
  }
  log_default("scanVaultEvents: total entries found:", events.length);
  return events;
}

// src/graph-builder.ts
var GRAPH_HEIGHT = 200;
var LANE_COUNT = MOOD_LEVELS.length;
var LANE_HEIGHT = GRAPH_HEIGHT / LANE_COUNT;
var MOOD_BAR_HEIGHT = Math.round(LANE_HEIGHT * 0.6);
var MOOD_BAR_OFFSET = Math.round((LANE_HEIGHT - MOOD_BAR_HEIGHT) / 2);
var DATE_HEADER_HEIGHT = 44;
var MIN_MONTH_LABEL_PX = 55;
var LABEL_FONT_SIZE = 10;
var LABEL_LINE_HEIGHT_PX = 12;
var LABEL_INNER_H_PAD = 14;
var LABEL_INNER_V_PAD = 8;
var LABEL_ROW_GAP = 4;
var LABEL_H_PAD = 6;
var LEFT_PAD = 20;
var SVG_NS = "http://www.w3.org/2000/svg";
function svgEl(tag, attrs) {
  const el = document.createElementNS(SVG_NS, tag);
  if (attrs) {
    for (const [k, v] of Object.entries(attrs)) {
      el.setAttribute(k, v);
    }
  }
  return el;
}
function computeEntrySpans(days, vaultEvents) {
  var _a2, _b2;
  const sortedEntries = [...vaultEvents].sort(
    (a, b) => a.date.localeCompare(b.date)
  );
  const dayActiveEntry = [];
  {
    let ePtr = 0;
    let current;
    for (const day of days) {
      while (ePtr < sortedEntries.length && ((_b2 = (_a2 = sortedEntries[ePtr]) == null ? void 0 : _a2.date) != null ? _b2 : "") <= day.date) {
        current = sortedEntries[ePtr];
        ePtr++;
      }
      dayActiveEntry.push(current);
    }
  }
  const spans = [];
  let currentSpan = null;
  for (let i = 0; i < days.length; i++) {
    const activeEntry = dayActiveEntry[i];
    if (activeEntry && currentSpan && activeEntry.filePath === currentSpan.entry.filePath) {
      currentSpan.endIdx = i;
    } else if (activeEntry) {
      currentSpan = { entry: activeEntry, startIdx: i, endIdx: i };
      spans.push(currentSpan);
    } else {
      currentSpan = null;
    }
  }
  log_default(
    "computeEntrySpans:",
    spans.length,
    "span(s) from",
    vaultEvents.length,
    "vault entr(ies)"
  );
  return spans;
}
function buildGraphSvg(barWidth, days, vaultEvents, ctx) {
  var _a2, _b2, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l, _m, _n, _o;
  log_default(
    "buildGraphSvg: barWidth =",
    barWidth,
    ", days =",
    days.length,
    ", events =",
    vaultEvents.length
  );
  const buildStart = performance.now();
  const BAR_WIDTH = barWidth;
  const BAR_GAP = barGapFor(barWidth);
  const stride = BAR_WIDTH + BAR_GAP;
  const graphTop = DATE_HEADER_HEIGHT;
  const graphBottom = graphTop + GRAPH_HEIGHT;
  const eventsByDate = /* @__PURE__ */ new Map();
  for (const ev of vaultEvents) {
    eventsByDate.set(ev.date, ev);
  }
  const labelMetrics = /* @__PURE__ */ new Map();
  {
    const measureCanvas = document.createElement("canvas");
    const measureCtx = measureCanvas.getContext("2d");
    if (measureCtx) {
      measureCtx.font = `${LABEL_FONT_SIZE}px system-ui, sans-serif`;
    }
    const measureLine = (text) => measureCtx ? measureCtx.measureText(text).width : text.length * 6;
    for (const ev of eventsByDate.values()) {
      if (!ev.label) continue;
      const lines = ev.label.replace(/\\n/g, "\n").split("\n");
      const maxLineWidth = Math.max(...lines.map(measureLine));
      const width = Math.ceil(maxLineWidth) + LABEL_INNER_H_PAD;
      const height = lines.length * LABEL_LINE_HEIGHT_PX + LABEL_INNER_V_PAD;
      labelMetrics.set(ev.date, { lines, width, height });
    }
  }
  const eventLabelRows = /* @__PURE__ */ new Map();
  const rowMaxHeight = [];
  {
    const rowRightEdge = [];
    for (let i = 0; i < days.length; i++) {
      const day = days[i];
      if (!day) continue;
      const ev = eventsByDate.get(day.date);
      if (!(ev == null ? void 0 : ev.label)) continue;
      const metrics = labelMetrics.get(day.date);
      const labelWidth = (_a2 = metrics == null ? void 0 : metrics.width) != null ? _a2 : LABEL_INNER_H_PAD + 60;
      const labelHeight = (_b2 = metrics == null ? void 0 : metrics.height) != null ? _b2 : LABEL_LINE_HEIGHT_PX + LABEL_INNER_V_PAD;
      const cx = LEFT_PAD + i * stride + BAR_WIDTH / 2;
      const left = cx - labelWidth / 2;
      const right = cx + labelWidth / 2;
      let row = 0;
      while (row < rowRightEdge.length && ((_c = rowRightEdge[row]) != null ? _c : -Infinity) > left - LABEL_H_PAD) {
        row++;
      }
      rowRightEdge[row] = right;
      rowMaxHeight[row] = Math.max(
        (_d = rowMaxHeight[row]) != null ? _d : 0,
        labelHeight
      );
      eventLabelRows.set(day.date, row);
    }
  }
  const numLabelRows = Math.max(
    1,
    eventLabelRows.size > 0 ? Math.max(...eventLabelRows.values()) + 1 : 0
  );
  const labelAreaTop = graphBottom + 8;
  const rowTopY = [];
  {
    let y = labelAreaTop;
    for (let row = 0; row < numLabelRows; row++) {
      rowTopY[row] = y;
      y += ((_e = rowMaxHeight[row]) != null ? _e : LABEL_LINE_HEIGHT_PX + LABEL_INNER_V_PAD) + LABEL_ROW_GAP;
    }
  }
  const lastRowBottom = ((_f = rowTopY[numLabelRows - 1]) != null ? _f : labelAreaTop) + ((_g = rowMaxHeight[numLabelRows - 1]) != null ? _g : LABEL_LINE_HEIGHT_PX + LABEL_INNER_V_PAD);
  const totalHeight = lastRowBottom + 4;
  const graphWidth = days.length * stride - BAR_GAP + 40;
  const svg = svgEl("svg", {
    width: String(graphWidth),
    height: String(totalHeight),
    viewBox: `0 0 ${graphWidth} ${totalHeight}`,
    class: "daylio-graph-svg"
  });
  {
    let d = "";
    for (let lane = 1; lane < LANE_COUNT; lane++) {
      const y = graphTop + lane * LANE_HEIGHT;
      d += `M0 ${y}H${graphWidth}`;
    }
    svg.appendChild(svgEl("path", {
      d,
      class: "daylio-lane-divider"
    }));
  }
  {
    let sepPath = "";
    let currentMonth = "";
    let lastLabelX = -Infinity;
    for (let i = 0; i < days.length; i++) {
      const day = days[i];
      if (!day) continue;
      const monthStr = day.date.slice(0, 7);
      if (monthStr === currentMonth) continue;
      currentMonth = monthStr;
      const x = LEFT_PAD + i * stride;
      sepPath += `M${x - 2} 0V${graphBottom}`;
      if (x - lastLabelX >= MIN_MONTH_LABEL_PX) {
        lastLabelX = x;
        const monthDate = /* @__PURE__ */ new Date(day.date + "T00:00:00");
        const monthName = monthDate.toLocaleString("default", {
          month: "short"
        });
        const label = svgEl("text", {
          x: String(x + 2),
          y: "12",
          class: "daylio-month-label"
        });
        label.textContent = `${monthName} ${monthDate.getFullYear()}`;
        svg.appendChild(label);
      }
    }
    svg.appendChild(svgEl("path", {
      d: sepPath,
      class: "daylio-month-line"
    }));
  }
  const moodPaths = {
    rad: "",
    good: "",
    meh: "",
    bad: "",
    awful: ""
  };
  for (let i = 0; i < days.length; i++) {
    const day = days[i];
    if (!day) continue;
    const x = LEFT_PAD + i * stride;
    for (const entry of day.entries) {
      const laneIndex = MOOD_TO_LANE[entry.mood];
      const barY = graphTop + laneIndex * LANE_HEIGHT + MOOD_BAR_OFFSET;
      const rx = Math.min(2, BAR_WIDTH / 2);
      const w = BAR_WIDTH;
      const h = MOOD_BAR_HEIGHT;
      moodPaths[entry.mood] += `M${x + rx},${barY}h${w - 2 * rx}a${rx},${rx} 0 0 1 ${rx},${rx}v${h - 2 * rx}a${rx},${rx} 0 0 1 ${-rx},${rx}h${-(w - 2 * rx)}a${rx},${rx} 0 0 1 ${-rx},${-rx}v${-(h - 2 * rx)}a${rx},${rx} 0 0 1 ${rx},${-rx}Z`;
    }
  }
  for (const mood of MOOD_LEVELS) {
    if (!moodPaths[mood]) continue;
    svg.appendChild(svgEl("path", {
      d: moodPaths[mood],
      fill: ctx.moodColors[mood],
      class: "daylio-mood-bar"
    }));
  }
  for (let i = 0; i < days.length; i++) {
    const day = days[i];
    if (!day) continue;
    const dayOfMonth = parseInt(day.date.slice(8, 10), 10);
    const showTick = BAR_WIDTH >= 8 ? true : BAR_WIDTH >= 5 ? dayOfMonth % 5 === 1 || dayOfMonth === 1 : BAR_WIDTH >= 3 ? dayOfMonth % 10 === 1 || dayOfMonth === 1 : false;
    if (showTick) {
      const tick = svgEl("text", {
        x: String(LEFT_PAD + i * stride + BAR_WIDTH / 2),
        y: String(graphTop - 4),
        class: "daylio-date-tick"
      });
      tick.textContent = String(dayOfMonth);
      svg.appendChild(tick);
    }
  }
  for (let i = 0; i < days.length; i++) {
    const day = days[i];
    if (!day) continue;
    const event = eventsByDate.get(day.date);
    if (!(event == null ? void 0 : event.label)) continue;
    const eventLabel = event.label;
    const metrics = labelMetrics.get(day.date);
    const labelWidth = (_h = metrics == null ? void 0 : metrics.width) != null ? _h : LABEL_INNER_H_PAD + 60;
    const labelHeight = (_i = metrics == null ? void 0 : metrics.height) != null ? _i : LABEL_LINE_HEIGHT_PX + LABEL_INNER_V_PAD;
    const lines = (_j = metrics == null ? void 0 : metrics.lines) != null ? _j : [eventLabel];
    const cx = LEFT_PAD + i * stride + BAR_WIDTH / 2;
    const evRow = (_k = eventLabelRows.get(day.date)) != null ? _k : 0;
    const labelY = (_l = rowTopY[evRow]) != null ? _l : labelAreaTop;
    svg.appendChild(svgEl("line", {
      x1: String(cx),
      y1: "0",
      x2: String(cx),
      y2: String(labelY),
      class: "daylio-event-connector"
    }));
    const fo = svgEl("foreignObject", {
      x: String(cx - labelWidth / 2),
      y: String(labelY),
      width: String(labelWidth),
      height: String(labelHeight)
    });
    const labelDiv = document.createElement("div");
    labelDiv.className = "daylio-event-label";
    labelDiv.title = `${lines.join("\n")}
${event.date}
Click to open note`;
    for (let lineIdx = 0; lineIdx < lines.length; lineIdx++) {
      if (lineIdx > 0) {
        labelDiv.appendChild(document.createElement("br"));
      }
      labelDiv.appendChild(
        document.createTextNode((_m = lines[lineIdx]) != null ? _m : "")
      );
    }
    const filePath = event.filePath;
    labelDiv.addEventListener("click", (evt) => {
      evt.preventDefault();
      evt.stopPropagation();
      ctx.openFile(filePath);
    });
    fo.appendChild(labelDiv);
    svg.appendChild(fo);
  }
  const hoverDateLabel = svgEl("text", {
    class: "daylio-hover-date-label",
    y: String(graphBottom - 14),
    visibility: "hidden"
  });
  svg.appendChild(hoverDateLabel);
  const hoverNameLabel = svgEl("text", {
    class: "daylio-hover-name-label",
    y: String(graphBottom - 4),
    visibility: "hidden"
  });
  svg.appendChild(hoverNameLabel);
  const entrySpans = computeEntrySpans(days, vaultEvents);
  for (const span of entrySpans) {
    const g = svgEl("g", { class: "daylio-entry-group" });
    const startX = LEFT_PAD + span.startIdx * stride;
    const endX = LEFT_PAD + span.endIdx * stride + stride;
    g.appendChild(svgEl("rect", {
      x: String(startX),
      y: String(graphTop),
      width: String(endX - startX),
      height: String(GRAPH_HEIGHT),
      class: "daylio-range-bg"
    }));
    const filePath = span.entry.filePath;
    const clickHandler = (evt) => {
      evt.stopPropagation();
      ctx.openFile(filePath);
    };
    for (let i = span.startIdx; i <= span.endIdx; i++) {
      const dx = LEFT_PAD + i * stride;
      const dayOverlay = svgEl("rect", {
        x: String(dx),
        y: String(graphTop),
        width: String(stride),
        height: String(GRAPH_HEIGHT),
        class: "daylio-day-overlay"
      });
      dayOverlay.addEventListener("click", clickHandler);
      const dayDate = (_o = (_n = days[i]) == null ? void 0 : _n.date) != null ? _o : "";
      const entryName = filePath.split("/").pop().replace(/\.md$/i, "").replace(/^\d{4}-\d{2}-\d{2}[\s-]*/, "");
      const labelX = String(dx + BAR_WIDTH / 2);
      dayOverlay.addEventListener("mouseenter", () => {
        hoverDateLabel.textContent = dayDate;
        hoverDateLabel.setAttribute("x", labelX);
        hoverDateLabel.setAttribute("visibility", "visible");
        hoverNameLabel.textContent = entryName;
        hoverNameLabel.setAttribute("x", labelX);
        hoverNameLabel.setAttribute(
          "visibility",
          entryName ? "visible" : "hidden"
        );
      });
      dayOverlay.addEventListener("mouseleave", () => {
        hoverDateLabel.setAttribute("visibility", "hidden");
        hoverNameLabel.setAttribute("visibility", "hidden");
      });
      g.appendChild(dayOverlay);
    }
    svg.appendChild(g);
  }
  log_default(
    "buildGraphSvg: SVG dimensions",
    graphWidth,
    "\xD7",
    totalHeight,
    "px,",
    numLabelRows,
    "event label row(s),",
    (performance.now() - buildStart).toFixed(2),
    "ms"
  );
  return svg;
}

// src/graph-view.ts
var DaylioGraphView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.scrollContainer = null;
    this.scrollRatio = 1;
    this.zoomSlider = null;
    this.cachedDays = [];
    this.cachedVaultEvents = [];
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_DAYLIO;
  }
  getDisplayText() {
    return "Daylio Mood Graph";
  }
  getIcon() {
    return DAYLIO_ICON_ID;
  }
  async onOpen() {
    log_default("view opened");
    await this.renderGraph();
  }
  async onClose() {
    log_default("view closed");
    clearTimeout(this.zoomDebounceTimer);
    this.containerEl.empty();
  }
  /** Open a vault file by path, with error notice on failure. */
  openFile(filePath) {
    log_default("opening file:", filePath);
    const target = this.app.vault.getAbstractFileByPath(filePath);
    if (target instanceof import_obsidian2.TFile) {
      this.app.workspace.getLeaf(false).openFile(target);
    } else {
      console.warn("[daylio] file not found in vault:", filePath);
      new import_obsidian2.Notice(`Could not find note: ${filePath}`);
    }
  }
  /** Full re-render — called on open and when settings change. */
  async renderGraph() {
    log_default("renderGraph: starting full render");
    const container = this.containerEl.children[1];
    if (this.scrollContainer) {
      const maxScroll = this.scrollContainer.scrollWidth - this.scrollContainer.clientWidth;
      this.scrollRatio = maxScroll > 0 ? this.scrollContainer.scrollLeft / maxScroll : 1;
    }
    container.empty();
    container.addClass("daylio-graph-root");
    const csvPath = this.plugin.settings.csvPath;
    if (!csvPath) {
      log_default("renderGraph: no CSV path configured");
      container.createEl("p", {
        text: "No CSV path configured. Open the Daylio Mood Graph settings to set the path to your Daylio export.",
        cls: "daylio-graph-notice"
      });
      return;
    }
    log_default("renderGraph: CSV path is", csvPath);
    const csvFile = this.app.vault.getAbstractFileByPath(csvPath);
    if (!(csvFile instanceof import_obsidian2.TFile)) {
      log_default("renderGraph: CSV file not found at path:", csvPath);
      container.createEl("p", {
        text: `CSV file not found at "${csvPath}". Check the path in settings.`,
        cls: "daylio-graph-notice"
      });
      return;
    }
    let csvText;
    try {
      csvText = await this.app.vault.read(csvFile);
      log_default("renderGraph: CSV read successfully,", csvText.length, "chars");
    } catch (error) {
      console.warn("[daylio] renderGraph: failed to read CSV:", error);
      container.createEl("p", {
        text: "Failed to read the CSV file.",
        cls: "daylio-graph-notice"
      });
      return;
    }
    const allEntries = parseDaylioCsv(csvText);
    if (allEntries.length === 0) {
      log_default("renderGraph: no valid mood entries found in CSV");
      container.createEl("p", {
        text: "No valid mood entries found in the CSV.",
        cls: "daylio-graph-notice"
      });
      return;
    }
    const toolbar = container.createDiv({ cls: "daylio-graph-toolbar" });
    toolbar.createSpan({ text: "Zoom", cls: "daylio-zoom-label" });
    const stepZoom = (delta) => {
      const newWidth = Math.max(
        0.5,
        Math.min(16, this.plugin.settings.barWidth + delta)
      );
      if (newWidth === this.plugin.settings.barWidth) return;
      slider.value = String(newWidth);
      if (this.scrollContainer) {
        const viewportX = this.scrollContainer.clientWidth / 2;
        const svgX = this.scrollContainer.scrollLeft + viewportX;
        const oldBW = this.plugin.settings.barWidth;
        this.quickRedraw(newWidth, {
          svgX,
          viewportX,
          oldStride: oldBW + barGapFor(oldBW)
        });
      }
      void this.plugin.saveSettings();
    };
    const minusBtn = toolbar.createEl("button", {
      text: "\u2212",
      cls: "daylio-zoom-btn"
    });
    minusBtn.setAttribute("aria-label", "Zoom out");
    minusBtn.addEventListener("click", () => stepZoom(-0.5));
    const slider = toolbar.createEl("input");
    slider.type = "range";
    slider.min = "0.5";
    slider.max = "16";
    slider.step = "0.5";
    slider.value = String(this.plugin.settings.barWidth);
    slider.addClass("daylio-zoom-slider");
    this.zoomSlider = slider;
    slider.addEventListener("input", () => {
      const newWidth = parseFloat(slider.value);
      if (newWidth === this.plugin.settings.barWidth || !this.scrollContainer) return;
      const viewportX = this.scrollContainer.clientWidth / 2;
      const svgX = this.scrollContainer.scrollLeft + viewportX;
      const oldBW = this.plugin.settings.barWidth;
      this.quickRedraw(newWidth, {
        svgX,
        viewportX,
        oldStride: oldBW + barGapFor(oldBW)
      });
    });
    slider.addEventListener("change", async () => {
      await this.plugin.saveSettings();
    });
    const plusBtn = toolbar.createEl("button", {
      text: "+",
      cls: "daylio-zoom-btn"
    });
    plusBtn.setAttribute("aria-label", "Zoom in");
    plusBtn.addEventListener("click", () => stepZoom(0.5));
    this.cachedVaultEvents = scanVaultEvents(
      this.app,
      this.plugin.settings.eventScanDir || void 0
    );
    this.cachedDays = groupByDay(allEntries);
    log_default(
      "renderGraph: cached",
      this.cachedDays.length,
      "days and",
      this.cachedVaultEvents.length,
      "vault events"
    );
    const legend = container.createDiv({ cls: "daylio-graph-legend" });
    for (const mood of MOOD_LEVELS) {
      const item = legend.createDiv({ cls: "daylio-legend-item" });
      const swatch = item.createSpan({ cls: "daylio-legend-swatch" });
      swatch.style.backgroundColor = this.plugin.settings.moodColors[mood];
      item.createSpan({ text: mood, cls: "daylio-legend-label" });
    }
    this.scrollContainer = container.createDiv({
      cls: "daylio-graph-scroll"
    });
    this.setupDragPan(this.scrollContainer);
    this.scrollContainer.addEventListener(
      "wheel",
      (evt) => {
        evt.preventDefault();
        if (evt.ctrlKey) {
          const step = this.plugin.settings.barWidth <= 2 ? 0.5 : 1;
          const delta = evt.deltaY < 0 ? step : -step;
          const newWidth = Math.max(
            0.5,
            Math.min(
              16,
              this.plugin.settings.barWidth + delta
            )
          );
          if (newWidth !== this.plugin.settings.barWidth) {
            const rect = this.scrollContainer.getBoundingClientRect();
            const viewportX = evt.clientX - rect.left;
            const svgX = this.scrollContainer.scrollLeft + viewportX;
            const oldBW = this.plugin.settings.barWidth;
            this.quickRedraw(newWidth, {
              svgX,
              viewportX,
              oldStride: oldBW + barGapFor(oldBW)
            });
            clearTimeout(this.zoomDebounceTimer);
            this.zoomDebounceTimer = setTimeout(async () => {
              await this.plugin.saveSettings();
            }, 300);
          }
        } else {
          this.scrollContainer.scrollLeft += evt.deltaX + evt.deltaY;
        }
      },
      { passive: false }
    );
    this.scrollContainer.appendChild(this.buildSvg(this.plugin.settings.barWidth));
    requestAnimationFrame(() => {
      if (this.scrollContainer) {
        const maxScroll = this.scrollContainer.scrollWidth - this.scrollContainer.clientWidth;
        this.scrollContainer.scrollLeft = maxScroll * this.scrollRatio;
      }
    });
  }
  /**
   * Attach drag-to-pan behaviour to the horizontal scroll container.
   *
   * Left-mouse-drag translates to horizontal scroll.  A small drag
   * distance threshold (> 4 px) gates whether the pointer-up is
   * treated as a click so that vault-entry click handlers are not
   * triggered when the user releases the mouse after panning.
   *
   * Cursor changes:
   *   default          → grab   (via CSS on .daylio-graph-scroll)
   *   hovering entry   → pointer (via CSS on .daylio-entry-group)
   *   while panning    → grabbing (via class on document.body, !important
   *                               so it wins over child pointer cursors)
   */
  setupDragPan(scrollEl) {
    let isDragging = false;
    let startX = 0;
    let startScrollLeft = 0;
    let totalDragPx = 0;
    this.registerDomEvent(scrollEl, "mousedown", (evt) => {
      if (evt.button !== 0) return;
      isDragging = true;
      totalDragPx = 0;
      startX = evt.clientX;
      startScrollLeft = scrollEl.scrollLeft;
      document.body.classList.add("daylio-is-panning");
      evt.preventDefault();
    });
    this.registerDomEvent(document, "mousemove", (evt) => {
      if (!isDragging) return;
      const delta = startX - evt.clientX;
      totalDragPx = Math.abs(delta);
      scrollEl.scrollLeft = startScrollLeft + delta;
    });
    this.registerDomEvent(document, "mouseup", () => {
      if (!isDragging) return;
      isDragging = false;
      document.body.classList.remove("daylio-is-panning");
    });
    this.registerDomEvent(
      scrollEl,
      "click",
      (evt) => {
        if (totalDragPx > 4) {
          evt.stopPropagation();
          evt.preventDefault();
          totalDragPx = 0;
        }
      },
      { capture: true }
    );
  }
  /** Thin wrapper around the pure graph builder, passing context. */
  buildSvg(barWidth) {
    return buildGraphSvg(barWidth, this.cachedDays, this.cachedVaultEvents, {
      moodColors: this.plugin.settings.moodColors,
      openFile: (fp) => this.openFile(fp)
    });
  }
  /**
   * Replace SVG without full renderGraph() (no CSV read, no toolbar rebuild).
   * Anchor keeps the day column under the cursor pinned.
   */
  quickRedraw(newWidth, anchor) {
    if (!this.scrollContainer || this.cachedDays.length === 0) return;
    log_default(
      "quickRedraw:",
      this.plugin.settings.barWidth,
      "\u2192",
      newWidth,
      anchor ? "(cursor-anchored)" : "(ratio-based scroll)"
    );
    this.plugin.settings.barWidth = newWidth;
    if (this.zoomSlider) {
      this.zoomSlider.value = String(newWidth);
    }
    this.scrollContainer.empty();
    this.scrollContainer.appendChild(this.buildSvg(newWidth));
    requestAnimationFrame(() => {
      if (!this.scrollContainer) return;
      if (anchor) {
        const newStride = newWidth + barGapFor(newWidth);
        const newSvgX = 20 + (anchor.svgX - 20) * (newStride / anchor.oldStride);
        this.scrollContainer.scrollLeft = Math.max(
          0,
          newSvgX - anchor.viewportX
        );
      } else {
        const maxScroll = this.scrollContainer.scrollWidth - this.scrollContainer.clientWidth;
        this.scrollContainer.scrollLeft = maxScroll * this.scrollRatio;
      }
    });
  }
};

// src/settings-tab.ts
var import_obsidian3 = require("obsidian");
var DaylioSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    log_default("settings tab displayed");
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Daylio Mood Graph Settings" });
    const csvFiles = this.app.vault.getFiles().filter((f) => f.extension === "csv").sort((a, b) => a.path.localeCompare(b.path));
    const currentPath = this.plugin.settings.csvPath;
    new import_obsidian3.Setting(containerEl).setName("CSV file path").setDesc(
      csvFiles.length === 0 ? "No CSV files found in this vault. Add your Daylio export first, then reopen settings." : "Select the Daylio CSV export file from your vault."
    ).addDropdown((dropdown) => {
      dropdown.addOption("", "\u2014 choose a file \u2014");
      for (const file of csvFiles) {
        dropdown.addOption(file.path, file.path);
      }
      if (currentPath && !csvFiles.some((f) => f.path === currentPath)) {
        dropdown.addOption(
          currentPath,
          `${currentPath} \u26A0 not found`
        );
      }
      dropdown.setValue(currentPath).onChange(async (value) => {
        log_default("CSV path changed to:", value || "(none)");
        this.plugin.settings.csvPath = value;
        await this.plugin.saveSettings();
      });
    });
    const scanDirDesc = (dir) => {
      const base = "Vault-relative subdirectory to scan for event notes (e.g. entries). Leave blank to scan the whole vault.";
      const trimmed = dir.trim();
      if (!trimmed) return base;
      const prefix = trimmed.replace(/\/+$/, "") + "/";
      const count = this.app.vault.getMarkdownFiles().filter((f) => f.path.startsWith(prefix) && DATE_PREFIX_REGEX.test(f.basename)).length;
      return `${base} \u2014 ${count} valid date-prefixed note${count === 1 ? "" : "s"} found in "${trimmed}".`;
    };
    const scanDirSetting = new import_obsidian3.Setting(containerEl).setName("Event scan directory").setDesc(scanDirDesc(this.plugin.settings.eventScanDir)).addText(
      (text) => text.setPlaceholder("entries").setValue(this.plugin.settings.eventScanDir).onChange(async (value) => {
        const trimmed = value.trim();
        log_default(
          "event scan directory changed to:",
          trimmed || "(whole vault)"
        );
        this.plugin.settings.eventScanDir = trimmed;
        await this.plugin.saveSettings();
        scanDirSetting.setDesc(scanDirDesc(value));
      })
    );
    containerEl.createEl("h3", { text: "Mood Colours" });
    for (const mood of MOOD_LEVELS) {
      new import_obsidian3.Setting(containerEl).setName(mood.charAt(0).toUpperCase() + mood.slice(1)).addColorPicker(
        (picker) => picker.setValue(this.plugin.settings.moodColors[mood]).onChange(async (value) => {
          log_default("mood color changed:", mood, "\u2192", value);
          this.plugin.settings.moodColors[mood] = value;
          await this.plugin.saveSettings();
        })
      );
    }
    new import_obsidian3.Setting(containerEl).setName("Reset colours to defaults").addButton(
      (btn) => btn.setButtonText("Reset").onClick(async () => {
        log_default("resetting mood colors to defaults");
        this.plugin.settings.moodColors = {
          ...DEFAULT_MOOD_COLORS
        };
        await this.plugin.saveSettings();
        this.display();
      })
    );
  }
};

// src/main.ts
var DaylioGraphPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    log_default("plugin loading");
    await this.loadSettings();
    log_default("settings loaded:", this.settings);
    this.registerView(VIEW_TYPE_DAYLIO, (leaf) => {
      return new DaylioGraphView(leaf, this);
    });
    this.addRibbonIcon(DAYLIO_ICON_ID, "Open Daylio Mood Graph", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-daylio-mood-graph",
      name: "Open Daylio Mood Graph",
      callback: () => {
        this.activateView();
      }
    });
    this.addSettingTab(new DaylioSettingTab(this.app, this));
    log_default("plugin ready");
  }
  onunload() {
    log_default("plugin unloading");
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_DAYLIO);
  }
  async loadSettings() {
    const loaded = await this.loadData();
    log_default("raw data from storage:", loaded);
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      loaded
    );
    for (const mood of MOOD_LEVELS) {
      if (!this.settings.moodColors[mood]) {
        this.settings.moodColors[mood] = DEFAULT_MOOD_COLORS[mood];
      }
    }
    log_default("settings after merge:", this.settings);
  }
  async saveSettings() {
    log_default("saving settings:", this.settings);
    await this.saveData(this.settings);
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_DAYLIO)[0];
    if (!leaf) {
      log_default("no existing view leaf; opening in new right leaf");
      const newLeaf = workspace.getRightLeaf(false);
      if (!newLeaf) {
        log_default("could not obtain a right leaf; aborting");
        return;
      }
      await newLeaf.setViewState({
        type: VIEW_TYPE_DAYLIO,
        active: true
      });
      leaf = newLeaf;
    } else {
      log_default("reusing existing view leaf; re-rendering graph");
      if (leaf.view instanceof DaylioGraphView) {
        await leaf.view.renderGraph();
      }
    }
    workspace.revealLeaf(leaf);
  }
};
//# sourceMappingURL=main.js.map
