/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  DATE_PREFIX_REGEX: () => DATE_PREFIX_REGEX,
  MOOD_LEVELS: () => MOOD_LEVELS,
  collectStringItems: () => collectStringItems,
  computeAnchoredScroll: () => computeAnchoredScroll,
  computeEntrySpans: () => computeEntrySpans,
  computeIntrinsicWidth: () => computeIntrinsicWidth,
  computeRangeMoodProportions: () => computeRangeMoodProportions,
  computeStickyLabelPosition: () => computeStickyLabelPosition,
  default: () => DaylioGraphPlugin,
  groupByDay: () => groupByDay,
  isMoodLevel: () => isMoodLevel,
  packEventsIntoTracks: () => packEventsIntoTracks,
  packRangeEventsIntoTracks: () => packRangeEventsIntoTracks,
  parseCsvLine: () => parseCsvLine,
  parseDaylioCsv: () => parseDaylioCsv,
  parseEventString: () => parseEventString,
  parseFrontmatterDate: () => parseFrontmatterDate,
  scanVaultEvents: () => scanVaultEvents
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/types.ts
var import_obsidian = require("obsidian");

// src/daylio-face.svg
var daylio_face_default = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">\r\n  <circle cx="50" cy="50" r="48" fill="#4CAF50"/>\r\n  <circle cx="30" cy="52" r="7" fill="#1a1a1a"/>\r\n  <circle cx="70" cy="52" r="7" fill="#1a1a1a"/>\r\n  <path d="M35 65 Q50 74 65 65" stroke="#1a1a1a" stroke-width="7" fill="none" stroke-linecap="round"/>\r\n</svg>\r\n';

// src/types.ts
var DAYLIO_ICON_ID = "daylio-face";
var _a, _b;
var svgInner = (_b = (_a = daylio_face_default.match(/<svg[^>]*>([\s\S]*)<\/svg>/i)) == null ? void 0 : _a[1]) != null ? _b : daylio_face_default;
(0, import_obsidian.addIcon)(DAYLIO_ICON_ID, svgInner);
var MOOD_LEVELS = ["awful", "bad", "meh", "good", "rad"];
var DEFAULT_MOOD_COLORS = {
  rad: "#f78c1e",
  good: "#41a766",
  meh: "#9056a3",
  bad: "#5579a7",
  awful: "#6a777c"
};
var DEFAULT_SETTINGS = {
  csvPath: "",
  moodColors: { ...DEFAULT_MOOD_COLORS },
  barWidth: 8,
  eventScanDir: "",
  showEventLabels: true
};
var BAR_WIDTH_MIN = 0.25;
var BAR_WIDTH_MAX = 8;
var BAR_WIDTH_STEP = 0.25;
var BAR_WIDTH_FINE_THRESHOLD = 2;
var BAR_WIDTH_FINE_STEP = 0.25;
var BAR_WIDTH_COARSE_STEP = 0.5;
var BAR_WIDTH_YEAR_ONLY_THRESHOLD = 0.5;
var VIEW_TYPE_DAYLIO = "daylio-mood-graph-view";
function barGapFor(barWidth) {
  return barWidth >= 2 ? 2 : barWidth >= 1 ? 1 : 0;
}
var MOOD_TO_LANE = {
  rad: 0,
  good: 1,
  meh: 2,
  bad: 3,
  awful: 4
};

// src/graph-view.ts
var import_obsidian2 = require("obsidian");

// src/csv-parser.ts
function parseDaylioCsv(raw) {
  var _a2, _b2, _c, _d, _e, _f;
  const lines = raw.split(/\r?\n/).filter((line) => line.trim() !== "");
  if (lines.length < 2) {
    return [];
  }
  const entries = [];
  for (let i = 1; i < lines.length; i++) {
    const fields = parseCsvLine((_a2 = lines[i]) != null ? _a2 : "");
    const fullDate = (_b2 = fields[0]) == null ? void 0 : _b2.trim();
    const time = (_d = (_c = fields[3]) == null ? void 0 : _c.trim()) != null ? _d : "";
    const moodRaw = (_f = (_e = fields[4]) == null ? void 0 : _e.trim().toLowerCase()) != null ? _f : "";
    if (!fullDate || !isMoodLevel(moodRaw)) {
      continue;
    }
    entries.push({ date: fullDate, time, mood: moodRaw });
  }
  return entries;
}
function parseCsvLine(line) {
  const result = [];
  let current = "";
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const char = line[i];
    if (inQuotes) {
      if (char === '"') {
        if (i + 1 < line.length && line[i + 1] === '"') {
          current += '"';
          i++;
        } else {
          inQuotes = false;
        }
      } else {
        current += char;
      }
    } else {
      if (char === '"') {
        inQuotes = true;
      } else if (char === ",") {
        result.push(current);
        current = "";
      } else {
        current += char;
      }
    }
  }
  result.push(current);
  return result;
}
function isMoodLevel(value) {
  return MOOD_LEVELS.includes(value);
}
function groupByDay(entries) {
  const map = /* @__PURE__ */ new Map();
  for (const entry of entries) {
    const existing = map.get(entry.date);
    if (existing) {
      existing.push(entry);
    } else {
      map.set(entry.date, [entry]);
    }
  }
  const days = [];
  for (const [date, dayEntries] of map) {
    dayEntries.sort((a, b) => a.time.localeCompare(b.time));
    days.push({ date, entries: dayEntries });
  }
  days.sort((a, b) => a.date.localeCompare(b.date));
  return days;
}

// src/vault-scanner.ts
var DATE_PREFIX_REGEX = /^(\d{4}-\d{2}-\d{2})/;
var ISO_DATE_REGEX = /^\d{4}-\d{2}-\d{2}$/;
var DATE_RANGE_REGEX = /^(\d{4}-\d{2}-\d{2})\s*(?:->|\.\.|to)\s*(\d{4}-\d{2}-\d{2})$/;
var ONGOING_RANGE_REGEX = /^(\d{4}-\d{2}-\d{2})\s*(?:->|\.\.|to)\s*$/;
function parseEventString(rawStr, defaultStartDate, noteEndDate) {
  var _a2;
  const trimmed = rawStr.trim();
  if (!trimmed.includes("|")) {
    const isRange2 = Boolean(noteEndDate && noteEndDate >= defaultStartDate);
    return {
      label: trimmed,
      startDate: defaultStartDate,
      endDate: isRange2 ? noteEndDate : void 0,
      isRange: isRange2
    };
  }
  const parts = trimmed.split("|").map((p) => p.trim());
  const lastPart = (_a2 = parts[parts.length - 1]) != null ? _a2 : "";
  const rangeMatch = lastPart.match(DATE_RANGE_REGEX);
  if ((rangeMatch == null ? void 0 : rangeMatch[1]) && rangeMatch[2]) {
    const label = parts.slice(0, -1).join(" | ").trim();
    const startDate = rangeMatch[1];
    const endDate = rangeMatch[2];
    const isRange2 = endDate >= startDate;
    return {
      label,
      startDate,
      endDate: isRange2 ? endDate : void 0,
      isRange: isRange2
    };
  }
  const ongoingMatch = lastPart.match(ONGOING_RANGE_REGEX);
  if (ongoingMatch == null ? void 0 : ongoingMatch[1]) {
    const label = parts.slice(0, -1).join(" | ").trim();
    const startDate = ongoingMatch[1];
    const todayStr = formatISODate(/* @__PURE__ */ new Date());
    const endDate = todayStr >= startDate ? todayStr : startDate;
    return {
      label,
      startDate,
      endDate,
      isRange: true
    };
  }
  if (ISO_DATE_REGEX.test(lastPart)) {
    const label = parts.slice(0, -1).join(" | ").trim();
    const startDate = lastPart;
    const isRange2 = Boolean(noteEndDate && noteEndDate >= startDate);
    return {
      label,
      startDate,
      endDate: isRange2 ? noteEndDate : void 0,
      isRange: isRange2
    };
  }
  const isRange = Boolean(noteEndDate && noteEndDate >= defaultStartDate);
  return {
    label: trimmed,
    startDate: defaultStartDate,
    endDate: isRange ? noteEndDate : void 0,
    isRange
  };
}
function formatISODate(date) {
  const yyyy = date.getFullYear();
  const mm = String(date.getMonth() + 1).padStart(2, "0");
  const dd = String(date.getDate()).padStart(2, "0");
  return `${yyyy}-${mm}-${dd}`;
}
function parseFrontmatterDate(value) {
  if (typeof value === "string" && ISO_DATE_REGEX.test(value.trim())) {
    return value.trim();
  }
  return void 0;
}
function getDailyNotesFolder(app) {
  var _a2, _b2, _c;
  try {
    const internalPlugins = app.internalPlugins;
    const dailyNotes = (_a2 = internalPlugins == null ? void 0 : internalPlugins.getPluginById) == null ? void 0 : _a2.call(internalPlugins, "daily-notes");
    if (dailyNotes == null ? void 0 : dailyNotes.enabled) {
      const folder = (_c = (_b2 = dailyNotes == null ? void 0 : dailyNotes.instance) == null ? void 0 : _b2.options) == null ? void 0 : _c.folder;
      if (typeof folder === "string" && folder.trim()) {
        return folder.trim();
      }
    }
  } catch (e) {
  }
  return void 0;
}
function collectStringItems(val, out) {
  if (typeof val === "string" && val.trim()) {
    out.push(val.trim());
  } else if (Array.isArray(val)) {
    for (const item of val) {
      if (typeof item === "string" && item.trim()) {
        out.push(item.trim());
      }
    }
  }
}
function scanVaultEvents(app, scanDir) {
  const events = [];
  let effectiveDir = scanDir == null ? void 0 : scanDir.trim();
  if (!effectiveDir) {
    effectiveDir = getDailyNotesFolder(app);
  }
  const prefix = effectiveDir ? effectiveDir.replace(/\/+$/, "") + "/" : null;
  const files = app.vault.getMarkdownFiles().filter(
    (f) => prefix === null || f.path.startsWith(prefix)
  );
  for (const file of files) {
    const dateMatch = file.basename.match(DATE_PREFIX_REGEX);
    const cache = app.metadataCache.getFileCache(file);
    const frontmatter = cache == null ? void 0 : cache.frontmatter;
    const startProp = parseFrontmatterDate(frontmatter == null ? void 0 : frontmatter["daylio_start"]);
    const startDate = startProp != null ? startProp : dateMatch == null ? void 0 : dateMatch[1];
    if (!startDate) continue;
    const noteEndDate = parseFrontmatterDate(frontmatter == null ? void 0 : frontmatter["daylio_end"]);
    const rawItems = [];
    collectStringItems(frontmatter == null ? void 0 : frontmatter["daylio_event"], rawItems);
    collectStringItems(frontmatter == null ? void 0 : frontmatter["daylio_events"], rawItems);
    if (rawItems.length === 0) {
      events.push({
        date: startDate,
        filePath: file.path
      });
    } else {
      for (const rawItem of rawItems) {
        const parsed = parseEventString(rawItem, startDate, noteEndDate);
        events.push({
          date: parsed.startDate,
          endDate: parsed.endDate,
          isRange: parsed.isRange,
          label: parsed.label,
          filePath: file.path
        });
      }
    }
  }
  return events;
}

// src/graph-builder.ts
var GRAPH_HEIGHT = 200;
var LANE_COUNT = MOOD_LEVELS.length;
var LANE_HEIGHT = GRAPH_HEIGHT / LANE_COUNT;
var MOOD_BAR_FILL_RATIO = 0.6;
var MOOD_BAR_HEIGHT = Math.round(LANE_HEIGHT * MOOD_BAR_FILL_RATIO);
var MOOD_BAR_OFFSET = Math.round((LANE_HEIGHT - MOOD_BAR_HEIGHT) / 2);
var DATE_HEADER_HEIGHT = 18;
var MIN_MONTH_LABEL_PX = 55;
var LABEL_FONT_SIZE = 10;
var BAR_CORNER_RADIUS_MAX = 2;
var SEPARATOR_X_OFFSET = 2;
var MONTH_LABEL_Y = 13;
var SVG_BOTTOM_PAD = 4;
var DATE_TICK_OFFSET = 4;
var DATE_TICK_THRESHOLD_FULL = BAR_WIDTH_MAX;
var DATE_TICK_THRESHOLD_COARSE = 5;
var DATE_TICK_THRESHOLD_MEDIUM = 3;
var DATE_TICK_INTERVAL_COARSE = 5;
var DATE_TICK_INTERVAL_FINE = 10;
var HOVER_DATE_LABEL_OFFSET = 14;
var HOVER_NAME_LABEL_OFFSET = 4;
var LEFT_PAD = 20;
var RIGHT_PAD = 20;
function computeStickyLabelPosition(params) {
  const { x1, x2, cardX, cardW, pillW, isCallout, visibleLeft, padding = 8 } = params;
  if (visibleLeft > x1 && visibleLeft < x2 - padding) {
    const minWidth = isCallout ? cardW : Math.min(cardW, 40);
    const maxStickyX = x2 - minWidth;
    const stickyX = Math.max(x1, Math.min(visibleLeft + padding, maxStickyX));
    const width = isCallout ? cardW : Math.max(20, x2 - stickyX);
    return {
      x: Math.round(stickyX),
      width: Math.round(width),
      isSticky: true
    };
  }
  return {
    x: Math.round(cardX),
    width: Math.round(isCallout ? cardW : pillW),
    isSticky: false
  };
}
var SVG_NS = "http://www.w3.org/2000/svg";
function svgEl(tag, attrs) {
  const el = document.createElementNS(SVG_NS, tag);
  if (attrs) {
    for (const [k, v] of Object.entries(attrs)) {
      el.setAttribute(k, v);
    }
  }
  return el;
}
function computeEntrySpans(days, vaultEvents) {
  var _a2, _b2;
  const sortedEntries = [...vaultEvents].sort(
    (a, b) => a.date.localeCompare(b.date)
  );
  const dayActiveEntry = [];
  {
    let ePtr = 0;
    let current;
    for (const day of days) {
      while (ePtr < sortedEntries.length && ((_b2 = (_a2 = sortedEntries[ePtr]) == null ? void 0 : _a2.date) != null ? _b2 : "") <= day.date) {
        current = sortedEntries[ePtr];
        ePtr++;
      }
      dayActiveEntry.push(current);
    }
  }
  const spans = [];
  let currentSpan = null;
  for (let i = 0; i < days.length; i++) {
    const activeEntry = dayActiveEntry[i];
    if (activeEntry && currentSpan && activeEntry.filePath === currentSpan.entry.filePath) {
      currentSpan.endIdx = i;
    } else if (activeEntry) {
      currentSpan = { entry: activeEntry, startIdx: i, endIdx: i };
      spans.push(currentSpan);
    } else {
      currentSpan = null;
    }
  }
  return spans;
}
function computeRangeMoodProportions(days, startIdx, endIdx) {
  const counts = {
    rad: 0,
    good: 0,
    meh: 0,
    bad: 0,
    awful: 0
  };
  let totalEntries = 0;
  const safeStart = Math.max(0, Math.min(startIdx, days.length - 1));
  const safeEnd = Math.max(safeStart, Math.min(endIdx, days.length - 1));
  for (let i = safeStart; i <= safeEnd; i++) {
    const day = days[i];
    if (!day) continue;
    for (const entry of day.entries) {
      if (entry && entry.mood in counts) {
        counts[entry.mood]++;
        totalEntries++;
      }
    }
  }
  const totalDays = safeEnd - safeStart + 1;
  const proportions = MOOD_LEVELS.map((mood) => ({
    mood,
    count: counts[mood],
    percentage: totalEntries > 0 ? counts[mood] / totalEntries * 100 : 0
  }));
  return {
    proportions,
    totalEntries,
    totalDays
  };
}
function packEventsIntoTracks(vaultEvents, days, stride = 10, barWidth = 8, measureTextFn) {
  if (days.length === 0) return { spans: [], trackCount: 0 };
  const dateIdxMap = /* @__PURE__ */ new Map();
  for (let i = 0; i < days.length; i++) {
    const d = days[i];
    if (d) dateIdxMap.set(d.date, i);
  }
  const validItems = [];
  for (const ev of vaultEvents) {
    if (!ev.label) continue;
    const startIdx = dateIdxMap.get(ev.date);
    if (startIdx === void 0) continue;
    let endIdx = ev.endDate ? dateIdxMap.get(ev.endDate) : startIdx;
    if (endIdx === void 0) {
      const lastDay = days[days.length - 1];
      if (lastDay && ev.endDate && ev.endDate >= lastDay.date) {
        endIdx = days.length - 1;
      } else {
        endIdx = startIdx;
      }
    }
    if (endIdx < startIdx) {
      endIdx = startIdx;
    }
    const isRange = endIdx > startIdx;
    const textWidth = measureTextFn ? Math.ceil(measureTextFn(ev.label)) + 6 : ev.label.length * 6 + 6;
    const x1 = LEFT_PAD + startIdx * stride;
    const x2 = LEFT_PAD + endIdx * stride + barWidth;
    const barWidthPx = Math.max(barWidth, x2 - x1);
    const cardWidth = textWidth + 8;
    const isCallout = barWidthPx < cardWidth;
    let cardX = x1;
    let cardW = barWidthPx;
    let visualStartX = x1;
    let visualEndX = x2;
    if (isCallout) {
      const cx = (x1 + x2) / 2;
      cardX = Math.max(4, Math.round(cx - cardWidth / 2));
      cardW = cardWidth;
      visualStartX = Math.min(x1, cardX);
      visualEndX = Math.max(x2, cardX + cardWidth);
    }
    validItems.push({
      event: ev,
      startIdx,
      endIdx,
      isRange,
      textWidth,
      isCallout,
      cardX,
      cardW,
      visualStartX,
      visualEndX
    });
  }
  const rangeItems = validItems.filter((i) => i.isRange);
  const pointItems = validItems.filter((i) => !i.isRange);
  rangeItems.sort(
    (a, b) => a.startIdx - b.startIdx || b.endIdx - b.startIdx - (a.endIdx - a.startIdx) || a.visualStartX - b.visualStartX
  );
  pointItems.sort(
    (a, b) => a.startIdx - b.startIdx || a.visualStartX - b.visualStartX
  );
  const spans = [];
  const trackIntervals = [];
  const PADDING = 6;
  function assignTrack(item) {
    let trackIdx = 0;
    while (true) {
      if (trackIdx >= trackIntervals.length) {
        trackIntervals.push([{ startX: item.visualStartX, endX: item.visualEndX }]);
        return trackIdx;
      }
      const intervals = trackIntervals[trackIdx];
      let hasCollision = false;
      for (const interval of intervals) {
        if (!(item.visualEndX + PADDING <= interval.startX || item.visualStartX >= interval.endX + PADDING)) {
          hasCollision = true;
          break;
        }
      }
      if (!hasCollision) {
        intervals.push({ startX: item.visualStartX, endX: item.visualEndX });
        return trackIdx;
      }
      trackIdx++;
    }
  }
  for (const item of rangeItems) {
    const trackIdx = assignTrack(item);
    spans.push({
      event: item.event,
      startIdx: item.startIdx,
      endIdx: item.endIdx,
      trackIdx,
      textWidth: item.textWidth,
      isRange: true,
      isCallout: item.isCallout,
      cardX: item.cardX,
      cardW: item.cardW
    });
  }
  for (const item of pointItems) {
    const trackIdx = assignTrack(item);
    spans.push({
      event: item.event,
      startIdx: item.startIdx,
      endIdx: item.endIdx,
      trackIdx,
      textWidth: item.textWidth,
      isRange: false,
      isCallout: item.isCallout,
      cardX: item.cardX,
      cardW: item.cardW
    });
  }
  return { spans, trackCount: trackIntervals.length };
}
var packRangeEventsIntoTracks = (vaultEvents, days) => {
  return packEventsIntoTracks(vaultEvents, days, 10, 8);
};
function buildGraphSvg(barWidth, days, vaultEvents, ctx) {
  var _a2, _b2, _c, _d, _e, _f;
  const BAR_WIDTH = barWidth;
  const BAR_GAP = barGapFor(barWidth);
  const stride = BAR_WIDTH + BAR_GAP;
  const graphTop = DATE_HEADER_HEIGHT;
  const graphBottom = graphTop + GRAPH_HEIGHT;
  const RANGE_TRACK_HEIGHT = 30;
  const RANGE_SWIMLANE_GAP = 8;
  const TOP_BAR_HEIGHT = 3;
  const TOP_BAR_Y_OFFSET = 2;
  const CALLOUT_GAP = 0;
  const CALLOUT_CARD_HEIGHT = 18;
  const CALLOUT_CARD_Y_OFFSET = TOP_BAR_Y_OFFSET + TOP_BAR_HEIGHT + CALLOUT_GAP;
  const WIDE_PILL_HEIGHT = 18;
  const WIDE_PILL_Y_OFFSET = CALLOUT_CARD_Y_OFFSET;
  const measureCanvas = document.createElement("canvas");
  const measureCtx = measureCanvas.getContext("2d");
  if (measureCtx) {
    measureCtx.font = `${LABEL_FONT_SIZE}px system-ui, sans-serif`;
  }
  const measureLine = (text) => measureCtx ? measureCtx.measureText(text).width : text.length * 6;
  const eventTracks = ctx.showEventLabels ? packEventsIntoTracks(vaultEvents, days, stride, BAR_WIDTH, measureLine) : { spans: [], trackCount: 0 };
  const ganttTop = graphBottom + RANGE_SWIMLANE_GAP;
  const ganttHeight = eventTracks.trackCount > 0 ? eventTracks.trackCount * RANGE_TRACK_HEIGHT : 0;
  const totalHeight = ganttHeight > 0 ? ganttTop + ganttHeight + SVG_BOTTOM_PAD + 4 : graphBottom + SVG_BOTTOM_PAD;
  const graphWidth = days.length * stride - BAR_GAP + LEFT_PAD + RIGHT_PAD;
  let maxVisualX = graphWidth;
  for (const span of eventTracks.spans) {
    const spanRight = span.isCallout ? span.cardX + span.cardW + RIGHT_PAD : LEFT_PAD + span.endIdx * stride + BAR_WIDTH + RIGHT_PAD;
    if (spanRight > maxVisualX) {
      maxVisualX = spanRight;
    }
  }
  const svgWidth = Math.max(maxVisualX, (_a2 = ctx.minWidth) != null ? _a2 : 0);
  const svg = svgEl("svg", {
    width: String(svgWidth),
    height: String(totalHeight),
    viewBox: `0 0 ${svgWidth} ${totalHeight}`,
    class: "daylio-graph-svg"
  });
  svg.appendChild(svgEl("rect", {
    x: "0",
    y: "0",
    width: String(svgWidth),
    height: String(graphTop),
    class: "daylio-bg-segment daylio-bg-segment-header"
  }));
  svg.appendChild(svgEl("rect", {
    x: "0",
    y: String(graphTop),
    width: String(svgWidth),
    height: String(GRAPH_HEIGHT),
    class: "daylio-bg-segment daylio-bg-segment-graph"
  }));
  if (ganttHeight > 0) {
    svg.appendChild(svgEl("rect", {
      x: "0",
      y: String(graphBottom),
      width: String(svgWidth),
      height: String(totalHeight - graphBottom),
      class: "daylio-bg-segment daylio-bg-segment-labels"
    }));
  }
  {
    let d = "";
    for (let lane = 1; lane < LANE_COUNT; lane++) {
      const y = graphTop + lane * LANE_HEIGHT;
      d += `M0 ${y}H${graphWidth}`;
    }
    svg.appendChild(svgEl("path", {
      d,
      class: "daylio-lane-divider"
    }));
  }
  {
    const yearOnlyLabels = BAR_WIDTH <= BAR_WIDTH_YEAR_ONLY_THRESHOLD;
    let monthPath = "";
    let yearPath = "";
    let currentMonth = "";
    let lastLabelX = -Infinity;
    for (let i = 0; i < days.length; i++) {
      const day = days[i];
      if (!day) continue;
      const monthStr = day.date.slice(0, 7);
      if (monthStr === currentMonth) continue;
      currentMonth = monthStr;
      const x = LEFT_PAD + i * stride;
      const isYearStart = monthStr.endsWith("-01");
      if (isYearStart) {
        yearPath += `M${x - SEPARATOR_X_OFFSET} ${graphTop}V${graphBottom}`;
      } else {
        monthPath += `M${x - SEPARATOR_X_OFFSET} ${graphTop}V${graphBottom}`;
      }
      if (yearOnlyLabels && !isYearStart) continue;
      if (x - lastLabelX >= MIN_MONTH_LABEL_PX) {
        lastLabelX = x;
        if (yearOnlyLabels) {
          const year = monthStr.slice(0, 4);
          const label = svgEl("text", {
            x: String(x - SEPARATOR_X_OFFSET),
            y: String(MONTH_LABEL_Y),
            "text-anchor": "middle",
            class: "daylio-month-label"
          });
          label.textContent = year;
          svg.appendChild(label);
        } else {
          const monthDate = /* @__PURE__ */ new Date(day.date + "T00:00:00");
          const monthName = monthDate.toLocaleString("default", {
            month: "short"
          });
          const label = svgEl("text", {
            x: String(x - SEPARATOR_X_OFFSET),
            y: String(MONTH_LABEL_Y),
            "text-anchor": "middle",
            class: "daylio-month-label"
          });
          label.textContent = `${monthName} ${monthDate.getFullYear()}`;
          svg.appendChild(label);
        }
      }
    }
    if (monthPath) {
      svg.appendChild(svgEl("path", {
        d: monthPath,
        class: "daylio-month-line"
      }));
    }
    if (yearPath) {
      svg.appendChild(svgEl("path", {
        d: yearPath,
        class: "daylio-year-line"
      }));
    }
  }
  const moodPaths = {
    rad: "",
    good: "",
    meh: "",
    bad: "",
    awful: ""
  };
  for (let i = 0; i < days.length; i++) {
    const day = days[i];
    if (!day) continue;
    const colX = LEFT_PAD + i * stride;
    const uniqueMoods = new Set(day.entries.map((e) => e.mood));
    for (const mood of uniqueMoods) {
      const lane = MOOD_TO_LANE[mood];
      const laneTop = graphTop + lane * LANE_HEIGHT;
      const y = laneTop + MOOD_BAR_OFFSET;
      const w = BAR_WIDTH;
      const h = MOOD_BAR_HEIGHT;
      const rx = Math.min(BAR_CORNER_RADIUS_MAX, w / 2, h / 2);
      moodPaths[mood] += `M${colX + rx},${y}h${w - 2 * rx}a${rx},${rx} 0 0 1 ${rx},${rx}v${h - 2 * rx}a${rx},${rx} 0 0 1 ${-rx},${rx}h${-(w - 2 * rx)}a${rx},${rx} 0 0 1 ${-rx},${-rx}v${-(h - 2 * rx)}a${rx},${rx} 0 0 1 ${rx},${-rx}Z`;
    }
  }
  for (const mood of MOOD_LEVELS) {
    if (!moodPaths[mood]) continue;
    svg.appendChild(svgEl("path", {
      d: moodPaths[mood],
      fill: ctx.moodColors[mood],
      class: "daylio-mood-bar"
    }));
  }
  for (let i = 0; i < days.length; i++) {
    const day = days[i];
    if (!day) continue;
    const dayOfMonth = parseInt(day.date.slice(8, 10), 10);
    const showTick = BAR_WIDTH >= DATE_TICK_THRESHOLD_FULL ? true : BAR_WIDTH >= DATE_TICK_THRESHOLD_COARSE ? dayOfMonth % DATE_TICK_INTERVAL_COARSE === 1 || dayOfMonth === 1 : BAR_WIDTH >= DATE_TICK_THRESHOLD_MEDIUM ? dayOfMonth % DATE_TICK_INTERVAL_FINE === 1 || dayOfMonth === 1 : false;
    if (showTick) {
      const tick = svgEl("text", {
        x: String(LEFT_PAD + i * stride + BAR_WIDTH / 2),
        y: String(graphTop - DATE_TICK_OFFSET),
        class: "daylio-date-tick"
      });
      tick.textContent = String(dayOfMonth);
      svg.appendChild(tick);
    }
  }
  if (ctx.showEventLabels && eventTracks.spans.length > 0) {
    const swimlaneGroup = svgEl("g", { class: "daylio-range-swimlanes" });
    const sortedSpans = [...eventTracks.spans].sort((a, b) => b.trackIdx - a.trackIdx);
    for (const span of sortedSpans) {
      const x1 = LEFT_PAD + span.startIdx * stride;
      const x2 = LEFT_PAD + span.endIdx * stride + BAR_WIDTH;
      const barWidthPx = x2 - x1;
      const pillWidth = Math.max(BAR_WIDTH, barWidthPx);
      const yTrack = ganttTop + span.trackIdx * RANGE_TRACK_HEIGHT;
      const pillGroup = svgEl("g", { class: "daylio-range-pill-group" });
      const moodSummary = computeRangeMoodProportions(
        days,
        span.startIdx,
        span.endIdx
      );
      const tooltipData = {
        label: (_b2 = span.event.label) != null ? _b2 : "",
        isRange: span.isRange,
        date: span.event.date,
        endDate: span.event.endDate,
        moodSummary
      };
      const yTop = span.isRange ? span.isCallout ? yTrack + TOP_BAR_Y_OFFSET : yTrack + WIDE_PILL_Y_OFFSET : yTrack + CALLOUT_CARD_Y_OFFSET;
      if (!span.isRange) {
        const cx = LEFT_PAD + span.startIdx * stride + BAR_WIDTH / 2;
        pillGroup.appendChild(svgEl("line", {
          x1: String(cx),
          y1: "0",
          x2: String(cx),
          y2: String(yTop),
          class: "daylio-event-connector"
        }));
        pillGroup.appendChild(svgEl("circle", {
          cx: String(cx),
          cy: String(yTop - TOP_BAR_HEIGHT),
          r: String(TOP_BAR_HEIGHT),
          class: "daylio-point-circle"
        }));
      } else {
        const cxStart = LEFT_PAD + span.startIdx * stride + BAR_WIDTH / 2;
        const cxEnd = LEFT_PAD + span.endIdx * stride + BAR_WIDTH / 2;
        pillGroup.appendChild(svgEl("line", {
          x1: String(cxStart),
          y1: "0",
          x2: String(cxStart),
          y2: String(yTop),
          class: "daylio-event-connector"
        }));
        pillGroup.appendChild(svgEl("line", {
          x1: String(cxEnd),
          y1: "0",
          x2: String(cxEnd),
          y2: String(yTop),
          class: "daylio-event-connector"
        }));
      }
      if (span.isRange) {
        const topBarY = yTrack + TOP_BAR_Y_OFFSET;
        const topBar = svgEl("rect", {
          class: "daylio-range-top-bar",
          x: String(x1),
          y: String(topBarY),
          width: String(pillWidth),
          height: String(TOP_BAR_HEIGHT),
          rx: "2",
          ry: "2"
        });
        pillGroup.appendChild(topBar);
      }
      if (span.isCallout) {
        if (span.isRange) {
          const cx = (x1 + x2) / 2;
          const stemY1 = yTrack + TOP_BAR_Y_OFFSET + TOP_BAR_HEIGHT;
          const stemY2 = yTrack + CALLOUT_CARD_Y_OFFSET;
          if (stemY2 > stemY1) {
            const stem = svgEl("line", {
              class: "daylio-range-callout-stem",
              x1: String(cx),
              y1: String(stemY1),
              x2: String(cx),
              y2: String(stemY2)
            });
            pillGroup.appendChild(stem);
          }
        }
        const foAttrs = {
          x: String(span.cardX),
          y: String(yTrack + CALLOUT_CARD_Y_OFFSET),
          width: String(span.cardW),
          height: String(CALLOUT_CARD_HEIGHT + 4),
          style: "overflow: visible;"
        };
        if (span.isRange) {
          foAttrs.class = "daylio-range-fo";
          foAttrs["data-x1"] = String(x1);
          foAttrs["data-x2"] = String(x2);
          foAttrs["data-card-x"] = String(span.cardX);
          foAttrs["data-card-w"] = String(span.cardW);
          foAttrs["data-pill-w"] = String(pillWidth);
          foAttrs["data-is-callout"] = "true";
        }
        const fo = svgEl("foreignObject", foAttrs);
        const div = document.createElement("div");
        div.className = "daylio-range-callout-card";
        div.textContent = (_c = span.event.label) != null ? _c : "";
        fo.appendChild(div);
        pillGroup.appendChild(fo);
      } else {
        const pillY = yTrack + WIDE_PILL_Y_OFFSET;
        const rect = svgEl("rect", {
          class: "daylio-range-pill",
          x: String(x1),
          y: String(pillY),
          width: String(pillWidth),
          height: String(WIDE_PILL_HEIGHT),
          rx: "4",
          ry: "4"
        });
        pillGroup.appendChild(rect);
        const foAttrs = {
          x: String(x1),
          y: String(pillY),
          width: String(pillWidth),
          height: String(WIDE_PILL_HEIGHT + 4),
          style: "overflow: visible;"
        };
        if (span.isRange) {
          foAttrs.class = "daylio-range-fo";
          foAttrs["data-x1"] = String(x1);
          foAttrs["data-x2"] = String(x2);
          foAttrs["data-card-x"] = String(x1);
          foAttrs["data-card-w"] = String(span.cardW);
          foAttrs["data-pill-w"] = String(pillWidth);
          foAttrs["data-is-callout"] = "false";
        }
        const fo = svgEl("foreignObject", foAttrs);
        const div = document.createElement("div");
        div.className = "daylio-range-pill-text";
        div.textContent = (_d = span.event.label) != null ? _d : "";
        fo.appendChild(div);
        pillGroup.appendChild(fo);
      }
      pillGroup.addEventListener("mouseenter", (evt) => {
        var _a3;
        (_a3 = ctx.onEventHover) == null ? void 0 : _a3.call(ctx, evt, tooltipData);
      });
      pillGroup.addEventListener("mousemove", (evt) => {
        var _a3;
        (_a3 = ctx.onEventMove) == null ? void 0 : _a3.call(ctx, evt);
      });
      pillGroup.addEventListener("mouseleave", () => {
        var _a3;
        (_a3 = ctx.onEventLeave) == null ? void 0 : _a3.call(ctx);
      });
      const filePath = span.event.filePath;
      pillGroup.addEventListener("click", (evt) => {
        evt.preventDefault();
        evt.stopPropagation();
        ctx.openFile(filePath);
      });
      swimlaneGroup.appendChild(pillGroup);
    }
    svg.appendChild(swimlaneGroup);
  }
  const hoverDateLabel = svgEl("text", {
    class: "daylio-hover-date-label",
    y: String(graphBottom - HOVER_DATE_LABEL_OFFSET),
    visibility: "hidden"
  });
  svg.appendChild(hoverDateLabel);
  const hoverNameLabel = svgEl("text", {
    class: "daylio-hover-name-label",
    y: String(graphBottom - HOVER_NAME_LABEL_OFFSET),
    visibility: "hidden"
  });
  svg.appendChild(hoverNameLabel);
  const entrySpans = computeEntrySpans(days, vaultEvents);
  for (const span of entrySpans) {
    const g = svgEl("g", { class: "daylio-entry-group" });
    const startX = LEFT_PAD + span.startIdx * stride;
    const endX = LEFT_PAD + span.endIdx * stride + stride;
    g.appendChild(svgEl("rect", {
      x: String(startX),
      y: String(graphTop),
      width: String(endX - startX),
      height: String(GRAPH_HEIGHT),
      class: "daylio-range-bg"
    }));
    const filePath = span.entry.filePath;
    const clickHandler = (evt) => {
      evt.stopPropagation();
      ctx.openFile(filePath);
    };
    for (let i = span.startIdx; i <= span.endIdx; i++) {
      const dx = LEFT_PAD + i * stride;
      const dayOverlay = svgEl("rect", {
        x: String(dx),
        y: String(graphTop),
        width: String(stride),
        height: String(GRAPH_HEIGHT),
        class: "daylio-day-overlay"
      });
      dayOverlay.addEventListener("click", clickHandler);
      const dayDate = (_f = (_e = days[i]) == null ? void 0 : _e.date) != null ? _f : "";
      const entryName = filePath.split("/").pop().replace(/\.md$/i, "").replace(/^\d{4}-\d{2}-\d{2}[\s-]*/, "");
      const labelX = String(dx + BAR_WIDTH / 2);
      dayOverlay.addEventListener("mouseenter", () => {
        hoverDateLabel.textContent = dayDate;
        hoverDateLabel.setAttribute("x", labelX);
        hoverDateLabel.setAttribute("visibility", "visible");
        hoverNameLabel.textContent = entryName;
        hoverNameLabel.setAttribute("x", labelX);
        hoverNameLabel.setAttribute(
          "visibility",
          entryName ? "visible" : "hidden"
        );
      });
      dayOverlay.addEventListener("mouseleave", () => {
        hoverDateLabel.setAttribute("visibility", "hidden");
        hoverNameLabel.setAttribute("visibility", "hidden");
      });
      g.appendChild(dayOverlay);
    }
    svg.appendChild(g);
  }
  return svg;
}

// src/scroll-math.ts
function computeAnchoredScroll(anchor, newStride, intrinsicSvgWidth, containerWidth) {
  const newSvgX = LEFT_PAD + (anchor.svgX - LEFT_PAD) * (newStride / anchor.oldStride);
  const rawScrollLeft = newSvgX - anchor.viewportX;
  const marginLeft = Math.max(0, -rawScrollLeft);
  const scrollLeft = Math.max(0, rawScrollLeft);
  const svgWidth = Math.max(
    intrinsicSvgWidth,
    scrollLeft + containerWidth - marginLeft,
    containerWidth + 1 - marginLeft
  );
  return { scrollLeft, marginLeft, svgWidth };
}
function computeIntrinsicWidth(dayCount, barWidth) {
  const gap = barGapFor(barWidth);
  const stride = barWidth + gap;
  return dayCount * stride - gap + LEFT_PAD + RIGHT_PAD;
}

// src/graph-view.ts
var DRAG_CLICK_THRESHOLD_PX = 4;
var SAVE_DEBOUNCE_MS = 300;
var DaylioGraphView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.scrollContainer = null;
    this.tooltipEl = null;
    this.scrollRatio = 1;
    this.zoomSlider = null;
    this.cachedDays = [];
    this.cachedVaultEvents = [];
    /** Pending requestAnimationFrame id for scroll-position restore after a
     *  quickRedraw.  Cancelled before each new quickRedraw so that only the
     *  most-recent anchor calculation takes effect, preventing stale RAF
     *  callbacks from snapping the scroll to wrong positions during rapid zoom. */
    this.scrollRafId = null;
    /** Pending requestAnimationFrame id for sticky range label updates. */
    this.stickyRafId = null;
    /** The scroll-left value that the pending RAF will apply.  Set
     *  synchronously by quickRedraw so that a subsequent wheel event
     *  (arriving before the RAF fires) reads the correct logical scroll
     *  position rather than the stale 0 left by scrollContainer.empty(). */
    this.intendedScrollLeft = null;
    /** Left margin on the SVG element, used to achieve "negative scroll"
     *  when the cursor-anchored position would require scrollLeft < 0.
     *  Set synchronously in quickRedraw; persists until the next redraw. */
    this.intendedMarginLeft = 0;
    /** Incremented at the start of every renderGraph() call.  Any suspended
     *  render that finds a newer generation has started aborts without
     *  writing to the DOM, preventing duplicate scroll containers (and the
     *  duplicate wheel listeners they carry). */
    this.renderGeneration = 0;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_DAYLIO;
  }
  getDisplayText() {
    return "Daylio mood graph";
  }
  getIcon() {
    return DAYLIO_ICON_ID;
  }
  async onOpen() {
    await this.renderGraph();
  }
  onClose() {
    clearTimeout(this.zoomDebounceTimer);
    if (this.stickyRafId !== null) {
      cancelAnimationFrame(this.stickyRafId);
    }
    this.containerEl.empty();
    return Promise.resolve();
  }
  /** Open a vault file by path, with error notice on failure. */
  openFile(filePath) {
    const target = this.app.vault.getAbstractFileByPath(filePath);
    if (target instanceof import_obsidian2.TFile) {
      void this.app.workspace.getLeaf(false).openFile(target);
    } else {
      console.warn("[daylio] file not found in vault:", filePath);
      new import_obsidian2.Notice(`Could not find note: ${filePath}`);
    }
  }
  /** Full re-render — called on open and when settings change. */
  async renderGraph() {
    const generation = ++this.renderGeneration;
    this.intendedMarginLeft = 0;
    const container = this.containerEl.children[1];
    if (this.scrollContainer) {
      const maxScroll = this.scrollContainer.scrollWidth - this.scrollContainer.clientWidth;
      this.scrollRatio = maxScroll > 0 ? this.scrollContainer.scrollLeft / maxScroll : 1;
    }
    container.empty();
    container.addClass("daylio-graph-root");
    this.tooltipEl = container.createDiv({ cls: "daylio-tooltip" });
    this.tooltipEl.style.display = "none";
    const csvPath = this.plugin.settings.csvPath;
    if (!csvPath) {
      container.createEl("p", {
        text: "No CSV path configured. Open the Daylio mood graph settings to set the path to your Daylio export.",
        cls: "daylio-graph-notice"
      });
      return;
    }
    const csvFile = this.app.vault.getAbstractFileByPath(csvPath);
    if (!(csvFile instanceof import_obsidian2.TFile)) {
      container.createEl("p", {
        text: `CSV file not found at "${csvPath}". Check the path in settings.`,
        cls: "daylio-graph-notice"
      });
      return;
    }
    let csvText;
    try {
      csvText = await this.app.vault.read(csvFile);
    } catch (error) {
      console.warn("[daylio] renderGraph: failed to read CSV:", error);
      container.createEl("p", {
        text: "Failed to read the CSV file.",
        cls: "daylio-graph-notice"
      });
      return;
    }
    if (generation !== this.renderGeneration) {
      return;
    }
    const allEntries = parseDaylioCsv(csvText);
    if (allEntries.length === 0) {
      container.createEl("p", {
        text: "No valid mood entries found in the CSV.",
        cls: "daylio-graph-notice"
      });
      return;
    }
    const toolbar = container.createDiv({ cls: "daylio-graph-toolbar" });
    toolbar.createSpan({ text: "Zoom", cls: "daylio-zoom-label" });
    const stepZoom = (delta) => {
      const newWidth = Math.max(
        BAR_WIDTH_MIN,
        Math.min(BAR_WIDTH_MAX, this.plugin.settings.barWidth + delta)
      );
      if (newWidth === this.plugin.settings.barWidth) return;
      slider.value = String(newWidth);
      this.quickRedraw(newWidth, this.getCenterAnchor());
      void this.plugin.saveSettings();
    };
    const minusBtn = toolbar.createEl("button", {
      text: "\u2212",
      cls: "daylio-zoom-btn"
    });
    minusBtn.setAttribute("aria-label", "Zoom out");
    minusBtn.addEventListener("click", () => stepZoom(-BAR_WIDTH_STEP));
    const slider = toolbar.createEl("input");
    slider.type = "range";
    slider.min = String(BAR_WIDTH_MIN);
    slider.max = String(BAR_WIDTH_MAX);
    slider.step = String(BAR_WIDTH_STEP);
    slider.value = String(this.plugin.settings.barWidth);
    slider.addClass("daylio-zoom-slider");
    this.zoomSlider = slider;
    slider.addEventListener("input", () => {
      const newWidth = parseFloat(slider.value);
      if (newWidth === this.plugin.settings.barWidth || !this.scrollContainer) return;
      this.quickRedraw(newWidth, this.getCenterAnchor());
    });
    slider.addEventListener("change", () => {
      void this.plugin.saveSettings();
    });
    const plusBtn = toolbar.createEl("button", {
      text: "+",
      cls: "daylio-zoom-btn"
    });
    plusBtn.setAttribute("aria-label", "Zoom in");
    plusBtn.addEventListener("click", () => stepZoom(BAR_WIDTH_STEP));
    const labelsLabel = toolbar.createEl("label", {
      cls: "daylio-labels-toggle"
    });
    const labelsCheck = labelsLabel.createEl("input");
    labelsCheck.type = "checkbox";
    labelsCheck.checked = this.plugin.settings.showEventLabels;
    labelsLabel.createSpan({ text: "Labels" });
    labelsCheck.addEventListener("change", () => {
      this.plugin.settings.showEventLabels = labelsCheck.checked;
      this.quickRedraw(this.plugin.settings.barWidth, this.getCenterAnchor());
      void this.plugin.saveSettings();
    });
    const refreshBtn = toolbar.createEl("button", {
      text: "\u21BA",
      cls: "daylio-zoom-btn"
    });
    refreshBtn.setAttribute("aria-label", "Refresh graph");
    refreshBtn.addEventListener("click", () => {
      void this.renderGraph();
    });
    toolbar.createSpan({
      text: `v${this.plugin.manifest.version}`,
      cls: "daylio-version-label"
    });
    this.cachedVaultEvents = scanVaultEvents(
      this.app,
      this.plugin.settings.eventScanDir || void 0
    );
    this.cachedDays = groupByDay(allEntries);
    const legend = container.createDiv({ cls: "daylio-graph-legend" });
    for (const mood of MOOD_LEVELS) {
      const item = legend.createDiv({ cls: "daylio-legend-item" });
      const swatch = item.createSpan({ cls: "daylio-legend-swatch" });
      swatch.style.backgroundColor = this.plugin.settings.moodColors[mood];
      item.createSpan({ text: mood, cls: "daylio-legend-label" });
    }
    this.scrollContainer = container.createDiv({
      cls: "daylio-graph-scroll"
    });
    this.setupDragPan(this.scrollContainer);
    let rightButtonHeld = false;
    this.scrollContainer.addEventListener("mousedown", (evt) => {
      if (evt.button === 2) rightButtonHeld = true;
    });
    this.registerDomEvent(document, "mouseup", (evt) => {
      if (evt.button === 2) rightButtonHeld = false;
    });
    this.scrollContainer.addEventListener("contextmenu", (evt) => {
      if (rightButtonHeld) evt.preventDefault();
    });
    this.scrollContainer.addEventListener(
      "wheel",
      (evt) => {
        var _a2;
        evt.preventDefault();
        evt.stopPropagation();
        evt.stopImmediatePropagation();
        if ((evt.ctrlKey || rightButtonHeld) && evt.deltaY !== 0) {
          const step = this.plugin.settings.barWidth <= BAR_WIDTH_FINE_THRESHOLD ? BAR_WIDTH_FINE_STEP : BAR_WIDTH_COARSE_STEP;
          const delta = evt.deltaY < 0 ? step : -step;
          const newWidth = Math.max(
            BAR_WIDTH_MIN,
            Math.min(
              BAR_WIDTH_MAX,
              this.plugin.settings.barWidth + delta
            )
          );
          if (newWidth !== this.plugin.settings.barWidth) {
            const rect = this.scrollContainer.getBoundingClientRect();
            const viewportX = evt.clientX - rect.left;
            const currentScrollLeft = (_a2 = this.intendedScrollLeft) != null ? _a2 : this.scrollContainer.scrollLeft;
            const svgX = currentScrollLeft + viewportX - this.intendedMarginLeft;
            const oldBW = this.plugin.settings.barWidth;
            this.quickRedraw(newWidth, {
              svgX,
              viewportX,
              oldStride: oldBW + barGapFor(oldBW)
            });
            clearTimeout(this.zoomDebounceTimer);
            this.zoomDebounceTimer = setTimeout(() => {
              void this.plugin.saveSettings();
            }, SAVE_DEBOUNCE_MS);
          }
        } else {
          this.scrollContainer.scrollLeft += evt.deltaX + evt.deltaY;
        }
      },
      { passive: false }
    );
    this.scrollContainer.addEventListener(
      "scroll",
      () => {
        this.scheduleUpdateStickyRangeLabels();
      },
      { passive: true }
    );
    this.scrollContainer.appendChild(this.buildSvg(this.plugin.settings.barWidth));
    requestAnimationFrame(() => {
      if (this.scrollContainer) {
        const maxScroll = this.scrollContainer.scrollWidth - this.scrollContainer.clientWidth;
        this.scrollContainer.scrollLeft = maxScroll * this.scrollRatio;
        this.updateStickyRangeLabels();
      }
    });
  }
  /**
   * Attach drag-to-pan behaviour to the horizontal scroll container.
   *
   * Left-mouse-drag translates to horizontal scroll.  A small drag
   * distance threshold (> 4 px) gates whether the pointer-up is
   * treated as a click so that vault-entry click handlers are not
   * triggered when the user releases the mouse after panning.
   *
   * Cursor changes:
   *   default          → grab   (via CSS on .daylio-graph-scroll)
   *   hovering entry   → pointer (via CSS on .daylio-entry-group)
   *   while panning    → grabbing (via class on document.body, !important
   *                               so it wins over child pointer cursors)
   */
  setupDragPan(scrollEl) {
    let isDragging = false;
    let startX = 0;
    let startScrollLeft = 0;
    let totalDragPx = 0;
    this.registerDomEvent(scrollEl, "mousedown", (evt) => {
      if (evt.button !== 0) return;
      isDragging = true;
      totalDragPx = 0;
      startX = evt.clientX;
      startScrollLeft = scrollEl.scrollLeft;
      this.intendedScrollLeft = null;
      document.body.classList.add("daylio-is-panning");
      evt.preventDefault();
    });
    this.registerDomEvent(document, "mousemove", (evt) => {
      if (!isDragging) return;
      const delta = startX - evt.clientX;
      totalDragPx = Math.abs(delta);
      scrollEl.scrollLeft = startScrollLeft + delta;
      this.intendedScrollLeft = null;
      this.updateStickyRangeLabels();
    });
    this.registerDomEvent(document, "mouseup", () => {
      if (!isDragging) return;
      isDragging = false;
      document.body.classList.remove("daylio-is-panning");
    });
    this.registerDomEvent(
      scrollEl,
      "click",
      (evt) => {
        if (totalDragPx > DRAG_CLICK_THRESHOLD_PX) {
          evt.stopPropagation();
          evt.preventDefault();
          totalDragPx = 0;
        }
      },
      { capture: true }
    );
  }
  /** Thin wrapper around the pure graph builder, passing context. */
  buildSvg(barWidth, minWidth) {
    return buildGraphSvg(barWidth, this.cachedDays, this.cachedVaultEvents, {
      moodColors: this.plugin.settings.moodColors,
      openFile: (fp) => this.openFile(fp),
      showEventLabels: this.plugin.settings.showEventLabels,
      minWidth,
      onEventHover: (evt, data) => this.showTooltip(evt, data),
      onEventMove: (evt) => this.positionTooltip(evt),
      onEventLeave: () => this.hideTooltip()
    });
  }
  /** Schedule an update of sticky range labels via RAF. */
  scheduleUpdateStickyRangeLabels() {
    if (this.stickyRafId !== null) return;
    this.stickyRafId = requestAnimationFrame(() => {
      this.stickyRafId = null;
      this.updateStickyRangeLabels();
    });
  }
  /**
   * Pins the label text of partially-visible range events to the visible
   * left edge of the viewport when their beginning is scrolled out of frame.
   */
  updateStickyRangeLabels() {
    var _a2, _b2, _c, _d, _e;
    if (!this.scrollContainer) return;
    const visibleLeft = this.scrollContainer.scrollLeft - this.intendedMarginLeft;
    const rangeFos = this.scrollContainer.querySelectorAll(
      ".daylio-range-fo"
    );
    for (let i = 0; i < rangeFos.length; i++) {
      const fo = rangeFos[i];
      if (!fo) continue;
      const x1 = parseFloat((_a2 = fo.getAttribute("data-x1")) != null ? _a2 : "0");
      const x2 = parseFloat((_b2 = fo.getAttribute("data-x2")) != null ? _b2 : "0");
      const cardX = parseFloat((_c = fo.getAttribute("data-card-x")) != null ? _c : String(x1));
      const cardW = parseFloat((_d = fo.getAttribute("data-card-w")) != null ? _d : "0");
      const pillW = parseFloat((_e = fo.getAttribute("data-pill-w")) != null ? _e : "0");
      const isCallout = fo.getAttribute("data-is-callout") === "true";
      const result = computeStickyLabelPosition({
        x1,
        x2,
        cardX,
        cardW,
        pillW,
        isCallout,
        visibleLeft
      });
      fo.setAttribute("x", String(result.x));
      fo.setAttribute("width", String(result.width));
    }
  }
  /** Display rich tooltip with event details and mood proportion bar. */
  showTooltip(event, data) {
    if (!this.tooltipEl || !this.scrollContainer) return;
    this.tooltipEl.empty();
    const titleEl = this.tooltipEl.createDiv({ cls: "daylio-tooltip-title" });
    titleEl.textContent = data.label;
    const datesEl = this.tooltipEl.createDiv({ cls: "daylio-tooltip-dates" });
    if (data.isRange && data.endDate) {
      const daysText = `${data.moodSummary.totalDays} day${data.moodSummary.totalDays === 1 ? "" : "s"}`;
      datesEl.textContent = `${data.date} \u2192 ${data.endDate} (${daysText})`;
    } else {
      datesEl.textContent = data.date;
    }
    if (data.isRange && data.moodSummary.totalEntries > 0) {
      const barEl = this.tooltipEl.createDiv({ cls: "daylio-tooltip-bar" });
      for (const prop of data.moodSummary.proportions) {
        if (prop.count === 0) continue;
        const seg = barEl.createDiv({ cls: "daylio-tooltip-bar-segment" });
        seg.style.width = `${prop.percentage.toFixed(1)}%`;
        seg.style.backgroundColor = this.plugin.settings.moodColors[prop.mood];
      }
      const legendEl = this.tooltipEl.createDiv({ cls: "daylio-tooltip-legend" });
      for (const prop of data.moodSummary.proportions) {
        if (prop.count === 0) continue;
        const item = legendEl.createSpan({ cls: "daylio-tooltip-legend-item" });
        const swatch = item.createSpan({ cls: "daylio-tooltip-swatch" });
        swatch.style.backgroundColor = this.plugin.settings.moodColors[prop.mood];
        item.appendText(`${prop.count} ${prop.mood}`);
      }
    } else if (data.isRange && data.moodSummary.totalEntries === 0) {
      const emptyEl = this.tooltipEl.createDiv({ cls: "daylio-tooltip-empty" });
      emptyEl.textContent = "No mood entries in this range";
    }
    this.tooltipEl.style.display = "block";
    this.positionTooltip(event);
  }
  /** Position the floating tooltip relative to the cursor inside the root container. */
  positionTooltip(event) {
    var _a2, _b2;
    if (!this.tooltipEl || !this.scrollContainer) return;
    const rootRect = (_b2 = (_a2 = this.scrollContainer.parentElement) == null ? void 0 : _a2.getBoundingClientRect()) != null ? _b2 : this.scrollContainer.getBoundingClientRect();
    const tooltipWidth = this.tooltipEl.offsetWidth || 200;
    const tooltipHeight = this.tooltipEl.offsetHeight || 80;
    let left = event.clientX - rootRect.left + 12;
    let top = event.clientY - rootRect.top + 12;
    if (left + tooltipWidth > rootRect.width - 12) {
      left = event.clientX - rootRect.left - tooltipWidth - 12;
    }
    if (top + tooltipHeight > rootRect.height - 12) {
      top = event.clientY - rootRect.top - tooltipHeight - 12;
    }
    this.tooltipEl.style.left = `${Math.max(8, left)}px`;
    this.tooltipEl.style.top = `${Math.max(8, top)}px`;
  }
  /** Hide the floating tooltip. */
  hideTooltip() {
    if (this.tooltipEl) {
      this.tooltipEl.style.display = "none";
    }
  }
  /**
   * Compute anchor parameters centered at the visible viewport midpoint.
   * Returns undefined if no scroll container is active.
   */
  getCenterAnchor() {
    var _a2;
    if (!this.scrollContainer) return void 0;
    const viewportX = this.scrollContainer.clientWidth / 2;
    const scrollLeft = (_a2 = this.intendedScrollLeft) != null ? _a2 : this.scrollContainer.scrollLeft;
    const svgX = scrollLeft + viewportX - this.intendedMarginLeft;
    const oldBW = this.plugin.settings.barWidth;
    return {
      svgX,
      viewportX,
      oldStride: oldBW + barGapFor(oldBW)
    };
  }
  /**
   * Replace SVG without full renderGraph() (no CSV read, no toolbar rebuild).
   * Anchor keeps the day column under the cursor pinned.
   */
  quickRedraw(newWidth, anchor) {
    if (!this.scrollContainer || this.cachedDays.length === 0) return;
    this.plugin.settings.barWidth = newWidth;
    if (this.zoomSlider) {
      this.zoomSlider.value = String(newWidth);
    }
    const newStride = newWidth + barGapFor(newWidth);
    const intrinsicSvgWidth = computeIntrinsicWidth(
      this.cachedDays.length,
      newWidth
    );
    const containerWidth = this.scrollContainer.clientWidth;
    let neededSvgWidth;
    if (anchor) {
      const result = computeAnchoredScroll(
        anchor,
        newStride,
        intrinsicSvgWidth,
        containerWidth
      );
      neededSvgWidth = result.svgWidth;
      this.intendedScrollLeft = result.scrollLeft;
      this.intendedMarginLeft = result.marginLeft;
    } else {
      const savedScrollLeft = this.scrollContainer.scrollLeft;
      this.intendedMarginLeft = 0;
      neededSvgWidth = Math.max(
        intrinsicSvgWidth,
        savedScrollLeft + containerWidth + 1
      );
      this.intendedScrollLeft = savedScrollLeft;
    }
    this.scrollContainer.empty();
    const svg = this.buildSvg(newWidth, neededSvgWidth);
    if (this.intendedMarginLeft > 0) {
      svg.style.marginLeft = `${this.intendedMarginLeft}px`;
    }
    this.scrollContainer.appendChild(svg);
    if (this.scrollRafId !== null) {
      cancelAnimationFrame(this.scrollRafId);
    }
    this.scrollRafId = requestAnimationFrame(() => {
      this.scrollRafId = null;
      if (!this.scrollContainer) return;
      if (this.intendedScrollLeft !== null) {
        this.scrollContainer.scrollLeft = this.intendedScrollLeft;
        this.intendedScrollLeft = null;
      } else {
        const maxScroll = this.scrollContainer.scrollWidth - this.scrollContainer.clientWidth;
        this.scrollContainer.scrollLeft = maxScroll * this.scrollRatio;
      }
      this.updateStickyRangeLabels();
    });
  }
};

// src/settings-tab.ts
var import_obsidian3 = require("obsidian");
var DaylioSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const csvFiles = this.app.vault.getFiles().filter((f) => f.extension === "csv").sort((a, b) => a.path.localeCompare(b.path));
    const currentPath = this.plugin.settings.csvPath;
    new import_obsidian3.Setting(containerEl).setName("CSV file path").setDesc(
      csvFiles.length === 0 ? "No CSV files found in this vault. Add your Daylio export first, then reopen settings." : "Select the Daylio CSV export file from your vault."
    ).addDropdown((dropdown) => {
      dropdown.addOption("", "\u2014 choose a file \u2014");
      for (const file of csvFiles) {
        dropdown.addOption(file.path, (0, import_obsidian3.normalizePath)(file.path));
      }
      if (currentPath && !csvFiles.some((f) => f.path === currentPath)) {
        dropdown.addOption(
          currentPath,
          `${currentPath} \u26A0 not found`
        );
      }
      dropdown.setValue(currentPath).onChange(async (value) => {
        this.plugin.settings.csvPath = value;
        await this.plugin.saveSettings();
      });
    });
    const scanDirDesc = (dir) => {
      const base = "Vault-relative subdirectory to scan for event notes (e.g. entries). Leave blank to scan the whole vault.";
      const trimmed = dir.trim();
      if (!trimmed) return base;
      const prefix = trimmed.replace(/\/+$/, "") + "/";
      const count = this.app.vault.getMarkdownFiles().filter((f) => f.path.startsWith(prefix) && DATE_PREFIX_REGEX.test(f.basename)).length;
      return `${base} \u2014 ${count} valid date-prefixed note${count === 1 ? "" : "s"} found in "${trimmed}".`;
    };
    const scanDirSetting = new import_obsidian3.Setting(containerEl).setName("Event scan directory").setDesc(scanDirDesc(this.plugin.settings.eventScanDir)).addText(
      (text) => text.setPlaceholder("entries").setValue(this.plugin.settings.eventScanDir).onChange(async (value) => {
        const trimmed = (0, import_obsidian3.normalizePath)(value.trim());
        this.plugin.settings.eventScanDir = trimmed;
        await this.plugin.saveSettings();
        scanDirSetting.setDesc(scanDirDesc(value));
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Show event labels").setDesc(
      "Display the floating label cards for notes that have a daylio_event frontmatter field. The column highlights and hover markers are always shown."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showEventLabels).onChange(async (value) => {
        this.plugin.settings.showEventLabels = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("Mood colours").setHeading();
    for (const mood of MOOD_LEVELS) {
      new import_obsidian3.Setting(containerEl).setName(mood.charAt(0).toUpperCase() + mood.slice(1)).addColorPicker(
        (picker) => picker.setValue(this.plugin.settings.moodColors[mood]).onChange(async (value) => {
          this.plugin.settings.moodColors[mood] = value;
          await this.plugin.saveSettings();
        })
      );
    }
    new import_obsidian3.Setting(containerEl).setName("Reset colours to defaults").addButton(
      (btn) => btn.setButtonText("Reset").onClick(async () => {
        this.plugin.settings.moodColors = {
          ...DEFAULT_MOOD_COLORS
        };
        await this.plugin.saveSettings();
        this.display();
      })
    );
  }
};

// src/main.ts
var DaylioGraphPlugin = class extends import_obsidian4.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_DAYLIO, (leaf) => {
      return new DaylioGraphView(leaf, this);
    });
    this.addRibbonIcon(DAYLIO_ICON_ID, "Open Daylio mood graph", () => {
      void this.activateView();
    });
    this.addCommand({
      id: "open-graph",
      name: "Open mood graph",
      callback: () => {
        void this.activateView();
      }
    });
    this.addSettingTab(new DaylioSettingTab(this.app, this));
  }
  /** Intentionally empty — Obsidian calls this on plugin unload but we
   *  have no teardown work beyond what `registerView` handles. */
  onunload() {
  }
  async loadSettings() {
    const loaded = await this.loadData();
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      loaded
    );
    for (const mood of MOOD_LEVELS) {
      if (!this.settings.moodColors[mood]) {
        this.settings.moodColors[mood] = DEFAULT_MOOD_COLORS[mood];
      }
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = workspace.getLeavesOfType(VIEW_TYPE_DAYLIO)[0];
    if (!leaf) {
      const newLeaf = workspace.getLeaf("split", "horizontal");
      if (!newLeaf) {
        return;
      }
      await newLeaf.setViewState({
        type: VIEW_TYPE_DAYLIO,
        active: true
      });
      leaf = newLeaf;
    } else {
      if (leaf.view instanceof DaylioGraphView) {
        await leaf.view.renderGraph();
      }
    }
    void workspace.revealLeaf(leaf);
  }
};
//# sourceMappingURL=main.js.map
